source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

# Core
gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'

# Authentication & Authorization
gem 'devise', '~> 4.9'
gem 'devise-jwt', '~> 0.11'
gem 'pundit', '~> 2.3'

# API
gem 'rack-cors'
gem 'jbuilder'

# Background Jobs
gem 'sidekiq', '~> 7.0'
gem 'redis', '~> 5.0'

# File Upload
gem 'aws-sdk-s3', require: false
gem 'image_processing', '~> 1.2'

# Pagination
gem 'kaminari', '~> 1.2'

# Search
gem 'pg_search', '~> 2.3'

# Analytics
gem 'groupdate', '~> 6.2'

# Security
gem 'rack-attack', '~> 6.7'
gem 'bcrypt', '~> 3.1.7'

# Performance
gem 'bootsnap', require: false

# Monitoring
gem 'skylight'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
  gem 'rspec-propcheck', '~> 0.5'
end

group :development do
  gem 'annotate', '~> 3.2'
  gem 'brakeman', require: false
  gem 'bundle-audit', require: false
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'shoulda-matchers', '~> 5.3'
  gem 'simplecov', require: false
  gem 'database_cleaner-active_record', '~> 2.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]
